2018-03-16 01:55:00,535 INFO generated testing report: /var/lib/jenkins/workspace/test_sinamail/selenium2/reports/2018-03-16_01-55-00_result.html [log.py:47]
2018-03-16 01:55:00,541 INFO read csv file [log.py:47]
2018-03-16 01:55:00,542 INFO username list: ['doris_test@sina.com', 'doris_test@sina.com', '', 'doris_test@sina.com'] [log.py:47]
2018-03-16 01:55:00,542 INFO password list: ['admin@123', '', 'admin@123', '123456'] [log.py:47]
2018-03-16 01:55:00,543 INFO host:http://172.17.1.207:5555/wd/hub,browser:chrome [log.py:47]
2018-03-16 01:55:05,578 INFO username: doris_test@sina.com, password:  [log.py:47]
2018-03-16 01:55:10,090 INFO host:http://172.17.1.207:5555/wd/hub,browser:chrome [log.py:47]
2018-03-16 01:55:15,053 INFO username: , password: admin@123 [log.py:47]
2018-03-16 01:55:18,505 INFO host:http://172.17.1.207:5555/wd/hub,browser:chrome [log.py:47]
2018-03-16 01:55:23,320 INFO username:doris_test@sina.com, password: admin@123 [log.py:47]
2018-03-16 01:55:49,249 INFO host:http://172.17.1.207:5555/wd/hub,browser:chrome [log.py:47]
2018-03-16 01:55:54,319 INFO username: doris_test@sina.com, password: 123456 [log.py:47]
2018-03-16 01:55:59,822 INFO none of wrong images [log.py:47]
2018-03-16 01:55:59,822 INFO flag is none [log.py:47]
2018-03-16 01:55:59,823 INFO host:http://172.17.1.207:5555/wd/hub,browser:chrome [log.py:47]
2018-03-16 01:56:01,690 INFO the newest report is 2018-03-16_01-55-00_result.html [log.py:47]
2018-03-16 01:56:01,690 INFO preparing send report /var/lib/jenkins/workspace/test_sinamail/selenium2/reports/2018-03-16_01-55-00_result.html [log.py:47]
2018-03-16 01:56:01,693 INFO attach reports [log.py:47]
2018-03-16 01:56:32,299 ERROR send email failed [log.py:53]
